[tools]
python = "3.14.2"
ruby = "3.4.2"
go = "1.25.5"
node = "25.2.1"
deno = "2.6.3"
bun = "1.3.5"

[hooks]
enter = "mise install -q"

[settings]
experimental = true

[tasks.random-member]
description = "メンバーをランダムに選ぶ"
run = "shuf -n 1 -e Alice Bob Charlie Dave"
