[tools]
python = "3.14.2"
ruby = "4.0.1"
go = "1.25.6"
node = "25.5.0"
deno = "2.6.6"
bun = "1.3.8"

[hooks]
enter = "mise install -q"

[settings]
experimental = true

[tasks.random-member]
description = "メンバーをランダムに選ぶ"
run = "shuf -n 1 -e Alice Bob Charlie Dave"
