[tools]
python = "3.14.3"
ruby = "4.0.1"
go = "1.25.7"
node = "25.6.1"
deno = "2.6.8"
bun = "1.3.9"

[hooks]
enter = "mise install -q"

[settings]
experimental = true

[tasks.random-member]
description = "メンバーをランダムに選ぶ"
run = "shuf -n 1 -e Alice Bob Charlie Dave"
